version: '3.7'
services:
  ifinslik_api:
    image: ifinslik_api:latest
    container_name: ifinslik_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8004
      - DATABASE_TYPE=SqlServer
      - DATABASE_CONNECTION_STRING=Server=147.139.191.88,1433; Database=IFINSLIK; User ID=sa; Password=Nimda321; Connection Timeout=0; Persist Security Info=True
      - KEY=IMS-Super-Secret
      - IV=1234567890123456
    ports:
      - "8004:8004"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
